name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    # if: false
    name: GitHub Actions Connected
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    
    - name: Install dependencies
      run: npm install
    
    - name: Verify Workflow Completed
      run: echo "GitHub Actions Workflow completed successfully."

    - name: Push artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-artifact-${{ github.sha }}
        path: reports/report.xml