name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    # if: false
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    
    - name: Install dependencies
      run: npm clean-install
    
    - name: Run linter
      run: npm run lint
    
    - name: Verify Linting Completed
      run: echo "Linting completed successfully."

    - name: Push artifact
      uses: actions/upload-artifact@v3
      with:
        name: lint-artifact
        path: reports/report.xml